name: deploy to ec2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: check-out code
      uses: actions/checkout@v3

    - name: deploy via ssh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd Learning-Management-System-Backend
          git pull origin main
          npm install
          pm2 restart backend
